export const poton = {
  label: "Poton",
  lineup: {
    saturday: [
      {
        label: "Armin van Buuren",
        start: "10:30",
        end: "12:00",
        image: "/acts/Armin.png",
        video: "https://www.youtube.com/embed/TxvpctgU_s8",
        info: "Five-time “World’s No. 1 DJ” and trance icon, Armin delivers euphoric, high-energy sets that have headlined festivals from Tomorrowland to Ultra. His uplifting melodies and impeccable mixing keep crowds dancing for hours.",
      },
      {
        label: "Kensington",
        start: "12:30",
        end: "14:00",
        image: "/acts/Kensington.png",
        video: "https://www.youtube.com/embed/IH77eOyV95o",
        info: "Rotterdam-born indie rock quintet known for soaring choruses and driving guitar riffs. Hits like “Streets” and “Riddles” showcase their knack for arena-ready hooks and emotionally charged lyricism.",
      },
      {
        label: "De Staat",
        start: "14:30",
        end: "16:30",
        image: "/acts/DeStaat.png",
        info: "Experimental rock outfit from Nijmegen, blending funky grooves with angular guitar work and theatrical stagecraft. Tracks like “Witch Doctor” and “Down Town” highlight their genre-bending approach and infectious energy.",
      },
      {
        label: "Navarone",
        start: "17:00",
        end: "18:30",
        image: "/acts/Navarone.png",
        info: "Utrecht’s hard-hitting rock four-piece, delivering riff-driven anthems and dynamic vocals. With a live reputation for raw intensity, they’re tailor-made for late-night main stages.",
      },
      {
        label: "Dotan",
        start: "19:15",
        end: "21:15",
        image: "/acts/Dotan.png",
        info: "Folk-pop singer-songwriter whose intimate voice and acoustic arrangements (notably on “Home”) have earned him platinum sales and sell-out shows. His heartfelt storytelling connects deeply on festival acoustic stages.",
      },
      {
        label: "Froukje",
        start: "22:00",
        end: "00:00",
        image: "/acts/Froukje.png",
        info: "Breakthrough pop singer Froukje Veenstra combines candid lyrics with catchy, synth-driven hooks. Since her 2021 debut, she’s become a voice of her generation—ideal for mid-day festival stages.",
      },
    ],
    sunday: [
      {
        label: "Martin Garrix",
        start: "11:00",
        end: "13:00",
        image: "/acts/Martin.png",
        info: "Broke through as a teenager with “Animals,” Martin Garrix has become one of the biggest names in EDM. His anthemic big-room tracks and stadium-sized drops make him a festival favorite across Europe.",
      },
      {
        label: "Within Temptation",
        start: "13:45",
        end: "15:45",
        image: "/acts/WithinTemptation.png",
        info: "Symphonic metal pioneers fronted by Sharon den Adel. Their cinematic soundscapes and operatic vocals (think “Ice Queen,” “Mother Earth”) translate into dramatic, visually stunning festival performances.",
      },
      {
        label: "Chef'Special",
        start: "16:30",
        end: "18:30",
        image: "/acts/ChefSpecial.png",
        info: "A four-piece from Haarlem mixing funk, pop, rock and hip-hop. Their upbeat, genre-fluid sound on songs like “Amigo” and “In Your Arms” makes for joyous, dance-floor-friendly live shows.",
      },
      {
        label: "Eefje de Visser",
        start: "19:15",
        end: "21:15",
        image: "/acts/Eefje.png",
        info: "Indie-pop artist crafting atmospheric, electronic-tinged songs. Her hypnotic vocals and lush production (as heard on “Ongeveer”) create a dreamlike vibe perfect for twilight festival slots.",
      },
      {
        label: "Spinvis",
        start: "22:00",
        end: "00:00",
        image: "/acts/Spinvis.png",
        info: "Erik de Jong performs under the moniker Spinvis, crafting poetic, collage-like songs that blend spoken-word snippets, lo-fi electronics and wistful pop. Since his debut album in 2002—recorded in his attic—he’s become a fixture of Dutch indie, renowned for narratives that feel both intimate and surreal. His live shows turn everyday observations into shared, dreamlike experiences.",
      },
    ],
  },
};

export const theLake = {
  label: "The Lake",
  lineup: {
    saturday: [
      {
        label: "Talent set 1",
        start: "10:00",
        end: "11:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 2",
        start: "11:30",
        end: "13:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 3",
        start: "13:30",
        end: "15:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 4",
        start: "15:30",
        end: "17:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 5",
        start: "17:30",
        end: "18:30",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 6",
        start: "19:15",
        end: "20:45",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 7",
        start: "21:30",
        end: "23:00",
        image: "/acts/talent.jpg",
        info: null,
      },
    ],
    sunday: [
      {
        label: "Talent set 1",
        start: "10:00",
        end: "11:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 2",
        start: "11:30",
        end: "13:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 3",
        start: "13:30",
        end: "15:00",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 4",
        start: "15:30",
        end: "17:30",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 5",
        start: "18:30",
        end: "19:45",
        image: "/acts/talent.jpg",
        info: null,
      },
      {
        label: "Talent set 6",
        start: "20:30",
        end: "22:30",
        image: "/acts/talent.jpg",
        info: null,
      },
    ],
  },
};

export const theClub = {
  label: "The Club",
  lineup: {
    saturday: [
      {
        label: "Comedy",
        start: "12:15",
        end: "13:00",
        image: "/acts/comedy.jpg",
        info: null,
      },
      {
        label: "Lecture",
        start: "13:45",
        end: "14:30",
        image: "/acts/lecture.jpg",
        info: null,
      },
      {
        label: "Theater",
        start: "15:15",
        end: "16:45",
        image: "/acts/theater.jpg",
        info: null,
      },
      {
        label: "Movie",
        start: "17:30",
        end: "19:30",
        image: "/acts/theater.jpg",
        info: null,
      },
      {
        label: "Performance",
        start: "20:15",
        end: "21:15",
        image: "/acts/the-club.jpg",
        info: null,
      },
      {
        label: "Illusionist",
        start: "22:00",
        end: "23:00",
        image: "/acts/the-club.jpg",
        info: null,
      },
    ],
    sunday: [
      {
        label: "Comedy",
        start: "12:00",
        end: "12:45",
        image: "/acts/comedy.jpg",
        info: null,
      },
      {
        label: "Lecture",
        start: "13:30",
        end: "14:30",
        image: "/acts/lecture.jpg",
        info: null,
      },
      {
        label: "Theater",
        start: "15:30",
        end: "16:30",
        image: "/acts/theater.jpg",
        info: null,
      },
      {
        label: "Movie",
        start: "17:30",
        end: "19:30",
        image: "/acts/theater.jpg",
        info: null,
      },
      {
        label: "Magic Show",
        start: "20:15",
        end: "21:45",
        image: "/acts/the-club.jpg",
        info: null,
      },
    ],
  },
};

export const hangar = {
  label: "Hangar",
  lineup: {
    saturday: [
      {
        label: "DJ SET 1",
        start: "10:00",
        end: "11:00",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 2",
        start: "11:00",
        end: "12:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 3",
        start: "12:30",
        end: "14:00",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 4",
        start: "14:00",
        end: "15:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 5",
        start: "15:30",
        end: "17:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 6",
        start: "17:30",
        end: "19:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 7",
        start: "19:30",
        end: "21:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 8",
        start: "21:30",
        end: "00:00",
        image: "/acts/dj.jpg",
        info: null,
      },
    ],
    sunday: [
      {
        label: "DJ SET 1",
        start: "10:00",
        end: "10:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 2",
        start: "10:30",
        end: "12:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 3",
        start: "12:30",
        end: "13:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 4",
        start: "13:30",
        end: "15:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 5",
        start: "15:30",
        end: "17:00",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 6",
        start: "17:00",
        end: "18:30",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 7",
        start: "18:30",
        end: "21:00",
        image: "/acts/dj.jpg",
        info: null,
      },
      {
        label: "DJ SET 8",
        start: "21:00",
        end: "00:00",
        image: "/acts/dj.jpg",
        info: null,
      },
    ],
  },
};
