import { ThemeProvider } from "@/context/theme-context";
import { OverlayProvider } from "@/context/overlay-context";
import type { Metadata } from "next";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import "./globals.css";
import MainLayout from "@/layout/main-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  const { lng } = await params;

  return (
    <html lang={lng} dir={dir(lng)} className="h-[100svh]">
      <body className="h-full flex flex-col">
        <ThemeProvider>
          <OverlayProvider>
            <MainLayout params={params}>{children}</MainLayout>
          </OverlayProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
