import { ThemeProvider } from "@/context/theme-context";
import type { Metadata } from "next";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  const { lng } = await params;

  return (
    <html lang={lng} dir={dir(lng)}>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
