import { stages } from "@/app/[lng]/schedule/stages";

type StageType = "Poton" | "The Lake" | "The Club" | "Hangar" | null;

export const pins = [
  {
    stage: stages[0] as StageType,
    x: 58,
    y: 127,
    size: 30,
    image: "/map/poton.svg",
  },
  {
    stage: stages[1] as StageType,
    x: 179,
    y: 96,
    size: 20,
    image: "/map/the-lake.svg",
  },
  {
    stage: stages[2] as StageType,
    x: 233,
    y: 84,
    size: 20,
    image: "/map/the-club.svg",
  },
  {
    stage: stages[3] as StageType,
    x: 313,
    y: 37,
    size: 20,
    image: "/map/hangar.svg",
  },
  {
    stage: null,
    x: 66,
    y: 175,
    size: 20,
    image: "/map/locker.svg",
  },
  {
    stage: null,
    x: 105,
    y: 175,
    size: 20,
    image: "/map/locker.svg",
  },
  {
    stage: null,
    x: 14,
    y: 170,
    size: 20,
    image: "/map/toilet.svg",
  },
  {
    stage: null,
    x: 164,
    y: 60,
    size: 20,
    image: "/map/toilet.svg",
  },
  {
    stage: null,
    x: 323,
    y: 55,
    size: 20,
    image: "/map/toilet.svg",
  },
  {
    stage: null,
    x: 50,
    y: 170,
    size: 20,
    image: "/map/merch.svg",
  },
  {
    stage: null,
    x: 95,
    y: 83,
    size: 20,
    image: "/map/merch.svg",
  },
  {
    stage: null,
    x: 217,
    y: 85,
    size: 20,
    image: "/map/merch.svg",
  },
  {
    stage: null,
    x: 26,
    y: 155,
    size: 20,
    image: "/map/bar.svg",
  },
  {
    stage: null,
    x: 167,
    y: 86,
    size: 20,
    image: "/map/bar.svg",
  },
  {
    stage: null,
    x: 245,
    y: 63,
    size: 20,
    image: "/map/bar.svg",
  },
  {
    stage: null,
    x: 281,
    y: 60,
    size: 20,
    image: "/map/bar.svg",
  },
  {
    stage: null,
    x: 26,
    y: 120,
    size: 30,
    image: "/map/food.svg",
  },
  {
    stage: null,
    x: 107,
    y: 85,
    size: 30,
    image: "/map/food.svg",
  },
  {
    stage: null,
    x: 76,
    y: 138,
    size: 30,
    image: "/map/ice-cream.svg",
  },
  {
    stage: null,
    x: 127,
    y: 84,
    size: 30,
    image: "/map/ice-cream.svg",
  },
  {
    stage: null,
    x: 208,
    y: 64,
    size: 30,
    image: "/map/ice-cream.svg",
  },
  {
    stage: null,
    x: 277,
    y: 30,
    size: 30,
    image: "/map/ice-cream.svg",
  },
  {
    stage: null,
    x: 43,
    y: 60,
    size: 30,
    image: "/map/first-aid.svg",
  },
  {
    stage: null,
    x: 210,
    y: 180,
    size: 70,
    image: "/map/entrance-exit.svg",
  },
];
